class MsgType:
    NEW_WORKER = "NEW_WORKER"
    EXIT_WORKER = "EXIT_WORKER"
    
    NEW_TRIAL = "NEW_TRIAL"
    COMPLETED_TRIAL = "COMPLETED_TRIAL"

    RESOURCES_ALLOCATION = "RESOURCES_ALLOCATION"
    RESOURCES_REALLOCATION = "RESOURCES_REALLOCATION"
    
    IMD_RES_TRAIN = "IMD_RES_TRAIN"
    